enemies:
  - type: zombie
    name: "Wandering Zombie"
    health: 10
    damage: 1
    speed: 0.05
    armor: 0
    vision_radius: 5
    color: [0, 255, 0]
    xp: 2
    amount: 3

  - type: skeleton
    name: "Bone Walker"
    health: 8
    damage: 2
    speed: 0.07
    armor: 1
    vision_radius: 7
    color: [155, 155, 155]
    xp: 4
    amount: 2
