# src/config.py
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
MAX_FPS = 144
TICK_RATE = 64

DUNGEON_HEIGHT = 100
DUNGEON_WIDTH = 100
DUNGEON_ROOMS = 5

NUM_TILES_X = 40  # Number of tiles horizontally
NUM_TILES_Y = 40  # Number of tiles vertically

VIEW_ZONE = 10

TILE_SIZE_X = SCREEN_WIDTH // NUM_TILES_X
TILE_SIZE_Y = SCREEN_HEIGHT // NUM_TILES_Y
