# src/config.py
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
MAX_FPS = 200
TICK_RATE = 64

DUNGEON_HEIGHT = 80
DUNGEON_WIDTH = 120
DUNGEON_ROOMS = DUNGEON_HEIGHT*DUNGEON_WIDTH/50

NUM_TILES_X = 400  # Number of tiles horizontally
NUM_TILES_Y = 400  # Number of tiles vertically

VIEW_ZONE = 20
LIGHT_RADIUS = 5

TILE_SIZE_X = SCREEN_WIDTH // NUM_TILES_X
TILE_SIZE_Y = SCREEN_HEIGHT // NUM_TILES_Y
